In [32]:
x = 2
for i in range(1, 101):
    x = x + i
    print(f"{i} + {x - i} = {x}")

1 + 2 = 3
2 + 3 = 5
3 + 5 = 8
4 + 8 = 12
5 + 12 = 17
6 + 17 = 23
7 + 23 = 30
8 + 30 = 38
9 + 38 = 47
10 + 47 = 57
11 + 57 = 68
12 + 68 = 80
13 + 80 = 93
14 + 93 = 107
15 + 107 = 122
16 + 122 = 138
17 + 138 = 155
18 + 155 = 173
19 + 173 = 192
20 + 192 = 212
21 + 212 = 233
22 + 233 = 255
23 + 255 = 278
24 + 278 = 302
25 + 302 = 327
26 + 327 = 353
27 + 353 = 380
28 + 380 = 408
29 + 408 = 437
30 + 437 = 467
31 + 467 = 498
32 + 498 = 530
33 + 530 = 563
34 + 563 = 597
35 + 597 = 632
36 + 632 = 668
37 + 668 = 705
38 + 705 = 743
39 + 743 = 782
40 + 782 = 822
41 + 822 = 863
42 + 863 = 905
43 + 905 = 948
44 + 948 = 992
45 + 992 = 1037
46 + 1037 = 1083
47 + 1083 = 1130
48 + 1130 = 1178
49 + 1178 = 1227
50 + 1227 = 1277
51 + 1277 = 1328
52 + 1328 = 1380
53 + 1380 = 1433
54 + 1433 = 1487
55 + 1487 = 1542
56 + 1542 = 1598
57 + 1598 = 1655
58 + 1655 = 1713
59 + 1713 = 1772
60 + 1772 = 1832
61 + 1832 = 1893
62 + 1893 = 1955
63 + 1955 = 2018
64 + 2018 = 2082
65 + 2082 = 2147
66 + 2147 = 2213
67 + 2213 = 2280
68 + 2280 = 2348
69 + 2348 = 2417
70 + 2417 = 2487
71 + 2487 = 2558
72 + 2558 = 2630
73 + 2630 = 2703
74 + 2703 = 2777
75 + 2777 = 2852
76 + 2852 = 2928
77 + 2928 = 3005
78 + 3005 = 3083
79 + 3083 = 3162
80 + 3162 = 3242
81 + 3242 = 3323
82 + 3323 = 3405
83 + 3405 = 3488
84 + 3488 = 3572
85 + 3572 = 3657
86 + 3657 = 3743
87 + 3743 = 3830
88 + 3830 = 3918
89 + 3918 = 4007
90 + 4007 = 4097
91 + 4097 = 4188
92 + 4188 = 4280
93 + 4280 = 4373
94 + 4373 = 4467
95 + 4467 = 4562
96 + 4562 = 4658
97 + 4658 = 4755
98 + 4755 = 4853
99 + 4853 = 4952
100 + 4952 = 5052

In [33]:
number = int(input("Введите число для таблицы умножения: "))

for i in range(1, 11):
    result = number * i
    print(f"{number} x {i} = {result}")

Введите число для таблицы умножения:  3

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

In [37]:
result = []
for i in range(2, 21):
    if i % 2 == 0:
        result.append(i)
print(f"Четные числа: {result}")

Четные числа: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [45]:
for i in range(10, -1, -1):
    if i == 10:
        print("Отсчет запущен!")
        print(i)
        continue
    print(i)
print("Пуск!")

Отсчет запущен!
10
9
8
7
6
5
4
3
2
1
0
Пуск!

In [47]:
x = input("Введите текст")

for i in range(len(x)):
    print(x[i])

Введите текст Здравствуйте

З
д
р
а
в
с
т
в
у
й
т
е